### ISSUE TITLE
License the code under an MIT License so that it can be integrated in jmxtrans-agent

### ISSUE THREAD

**Issue by cyrille-leclerc** [evgeniy-khist/jmxtrans-agent-elasticsearch#1]
Hello @evgeniy-khist,

There is demand to integrate your ElasticSearchOutputWriter in the core of jmxtrans-agent (1).

Could you license your code with an MIT License so that it is easier to merge it in jmxtrans-agent?

Cyrille

(1) https://groups.google.com/forum/#!topic/jmxtrans/jIyYctTW2go

**Comment by evgeniy-khist** [comment]
Hi @cyrille-leclerc,

Done. License updated to MIT License.

**Comment by cyrille-leclerc** [comment]
Many thanks @evgeniy-khist!

**Comment by cyrille-leclerc** [comment]
@evgeniy-khist FYI I have tracked the idea to integrate the feature in jmxtrans-agent with https://github.com/jmxtrans/jmxtrans-agent/issues/90
